name: CI for Project

on:
  push:
    branches:
      - main  # Run CI on every push to the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10  # Adjust based on your project requirements

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests shapely unittest

    # Make tests.sh executable
    - name: Make tests.sh executable
      run: chmod +x tests.sh

    # Run the tests
    - name: Run tests
      run: ./project/tests.sh

