name: CI for Project

on:
  push:
    branches:
      - main  # Run CI on every push to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'   # Specify the Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests shapely

    # Step 4: Make tests.sh executable
    - name: Make tests.sh executable
      run: chmod +x ./project/tests.sh

    # Step 5: Run tests
    - name: Run tests
      run: ./project/tests.sh
